// app/(marketing)/blog/solid-analytics-in-5-minutes/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { CodeBlock } from "../../site-chrome";

export const metadata: Metadata = {
  title: "Add product analytics to your SolidJS app in 5 minutes | Counted",
  description:
    "Drop @counted/sdk into any SolidJS app, auto-track page views on every route change, and fire custom events — no cookies, under 3KB gzipped.",
  openGraph: {
    title: "Add product analytics to your SolidJS app in 5 minutes",
    description:
      "Drop @counted/sdk into any SolidJS app, auto-track page views on every route change, and fire custom events — no cookies, under 3KB gzipped.",
    url: "https://counted.dev/blog/solid-analytics-in-5-minutes",
  },
};

export default function SolidAnalyticsPost() {
  return (
    <article className="prose prose-neutral dark:prose-invert max-w-2xl mx-auto py-16 px-4">
      <p className="text-sm text-muted-foreground uppercase tracking-wide mb-2">
        Quickstart · 5 min
      </p>
      <h1>Add product analytics to your SolidJS app in 5 minutes</h1>
      <p className="lead">
        {`@counted/sdk`} drops into any SolidJS app in a handful of lines — no
        cookie banner, no consent wall, no 50KB bundle. Here&apos;s the whole setup.
      </p>

      <h2>1. Get a project key</h2>
      <p>
        Create a project and copy its <code>ck_</code> client key — or provision
        one without signing up:
      </p>
      <CodeBlock>{`curl -X POST https://app.counted.dev/api/v0/provision`}</CodeBlock>
      <p>
        Add it to your <code>.env</code>. SolidJS uses Vite, which exposes{" "}
        <code>VITE_</code>-prefixed vars to the browser bundle:
      </p>
      <CodeBlock>{`# .env
VITE_COUNTED_PROJECT_KEY=ck_your_project_key`}</CodeBlock>
      <p>Client keys are write-only — safe to ship in the browser.</p>

      <h2>2. Install</h2>
      <CodeBlock>{`npm install @counted/sdk @solidjs/router`}</CodeBlock>
      <p>
        <code>@solidjs/router</code> is required for the page-view tracking in
        Step 4. If your project already uses it, skip the install.
      </p>

      <h2>3. Create an analytics module</h2>
      <p>
        Instantiate the SDK once and export the singleton. Any file in your app
        can import it — no React context needed.
      </p>
      <CodeBlock>{`// src/analytics.ts
import { Analytics } from "@counted/sdk";

export const analytics = new Analytics(
  import.meta.env.VITE_COUNTED_PROJECT_KEY,
  { host: "https://app.counted.dev" }
);`}</CodeBlock>

      <h2>4. Auto-track page views</h2>
      <p>
        SolidJS&apos;s <code>createEffect</code> re-runs reactively whenever its
        dependencies change. <code>useLocation()</code> from{" "}
        <code>@solidjs/router</code> is a reactive signal — accessing{" "}
        <code>location.pathname</code> inside an effect registers the dependency,
        so it fires on every route change automatically.
      </p>
      <p>
        Create a small component and place it inside{" "}
        <code>{"<Router>"}</code> in your root:
      </p>
      <CodeBlock>{`// src/components/PageViews.tsx
import { createEffect } from "solid-js";
import { useLocation } from "@solidjs/router";
import { analytics } from "../analytics";

export function PageViews() {
  const location = useLocation();
  createEffect(() => {
    analytics.track("page_view", { path: location.pathname });
  });
  return null;
}`}</CodeBlock>
      <CodeBlock>{`// src/App.tsx
import { Router, Route } from "@solidjs/router";
import { PageViews } from "./components/PageViews";
import { Home } from "./pages/Home";

export default function App() {
  return (
    <Router>
      <PageViews />
      <Route path="/" component={Home} />
      {/* other routes */}
    </Router>
  );
}`}</CodeBlock>
      <p>
        Every page your users visit now appears in the dashboard as a{" "}
        <code>page_view</code> event. Break it down by path, build funnels, or
        compare cohorts — all from the same event shape.
      </p>

      <h2>5. Track a custom event</h2>
      <p>
        Import the analytics singleton in any component. Properties are plain
        values — no user IDs, no PII.
      </p>
      <CodeBlock>{`// src/components/UpgradeButton.tsx
import { analytics } from "../analytics";

export function UpgradeButton() {
  return (
    <button onClick={() => analytics.track("upgrade_click", { plan: "pro" })}>
      Upgrade
    </button>
  );
}`}</CodeBlock>
      <p>
        Your event shows up on the dashboard within a second or two. Add as many
        properties as you want — breakdowns, time series, and funnels compose
        from whatever shape you send.
      </p>

      <hr />
      <p className="text-sm text-muted-foreground">
        Using React instead?{" "}
        <Link href="/blog/nextjs-analytics-in-5-minutes">
          Next.js quickstart
        </Link>{" "}
        ·{" "}
        <Link href="/blog/react-vite-analytics-in-5-minutes">
          React + Vite quickstart
        </Link>
        . Using a different framework?{" "}
        <Link href="/blog">See all quickstarts.</Link>
      </p>
    </article>
  );
}

// app/(marketing)/blog/preact-analytics-in-5-minutes/page.tsx
import { getPost } from "../posts";
import { postMetadata } from "../post-meta";
import { CodeBlock } from "../../site-chrome";
import { PostLayout, Lead, P, Step } from "../post-layout";

const meta = getPost("preact-analytics-in-5-minutes")!;

export const metadata = postMetadata(meta.slug);

export default function Post() {
  return (
    <PostLayout meta={meta}>
      <Lead>
        <code className="font-mono text-text-primary">@counted/sdk</code> drops
        into any Preact app in a handful of lines — no cookie banner, no consent
        wall, no 50KB bundle. Here's the whole setup: a singleton, auto page
        views on every route, and a custom event, in about five minutes.
      </Lead>

      <Step n={1} title="Get a project key">
        <P>
          Create a project and copy its <strong>client key</strong> (starts with{" "}
          <code className="font-mono text-text-primary">ck_</code>) — or mint one
          with no signup:
        </P>
        <div className="mt-3">
          <CodeBlock>{`curl -X POST https://app.counted.dev/api/v0/provision`}</CodeBlock>
        </div>
        <P>
          Add it to your{" "}
          <code className="font-mono text-text-primary">.env</code>. Preact's
          default Vite template exposes{" "}
          <code className="font-mono text-text-primary">VITE_</code>-prefixed
          vars to the browser bundle:
        </P>
        <div className="mt-3">
          <CodeBlock>{`# .env\nVITE_COUNTED_PROJECT_KEY=ck_your_project_key`}</CodeBlock>
        </div>
        <P>Client keys are write-only — safe to ship in the browser.</P>
      </Step>

      <Step n={2} title="Install the SDK">
        <div className="mt-1">
          <CodeBlock>{`npm install @counted/sdk`}</CodeBlock>
        </div>
      </Step>

      <Step n={3} title="Create an analytics module">
        <P>
          Create a singleton at{" "}
          <code className="font-mono text-text-primary">src/analytics.ts</code>.
          Import it anywhere in your app — no context or provider needed.
        </P>
        <div className="mt-3">
          <CodeBlock>{`// src/analytics.ts\nimport { Analytics } from "@counted/sdk";\n\nexport const analytics = new Analytics({\n  projectKey: import.meta.env.VITE_COUNTED_PROJECT_KEY,\n  host: "https://app.counted.dev",\n});`}</CodeBlock>
        </div>
      </Step>

      <Step n={4} title="Auto-track page views">
        <P>
          Create a small component that fires a{" "}
          <code className="font-mono text-text-primary">page_view</code> event
          whenever the route changes.{" "}
          <code className="font-mono text-text-primary">preact-iso</code>'s{" "}
          <code className="font-mono text-text-primary">useLocation()</code>{" "}
          returns a reactive location object — its{" "}
          <code className="font-mono text-text-primary">url</code> field updates
          on every client-side navigation.
        </P>
        <div className="mt-3">
          <CodeBlock>{`// src/components/PageViews.tsx\nimport { useEffect } from "preact/hooks";\nimport { useLocation } from "preact-iso";\nimport { analytics } from "../analytics";\n\nexport function PageViews() {\n  const { url } = useLocation();\n  useEffect(() => {\n    analytics.track("page_view", { path: url });\n  }, [url]);\n  return null;\n}`}</CodeBlock>
        </div>
        <P>
          Render it once inside your root{" "}
          <code className="font-mono text-text-primary">
            {"<LocationProvider>"}
          </code>{" "}
          in{" "}
          <code className="font-mono text-text-primary">src/index.tsx</code>:
        </P>
        <div className="mt-3">
          <CodeBlock>{`// src/index.tsx\nimport { LocationProvider, Router, Route } from "preact-iso";\nimport { PageViews } from "./components/PageViews";\nimport { Home } from "./pages/Home";\n\nexport function App() {\n  return (\n    <LocationProvider>\n      <PageViews />\n      <Router>\n        <Route path="/" component={Home} />\n      </Router>\n    </LocationProvider>\n  );\n}`}</CodeBlock>
        </div>
        <P>
          Every page your users visit now appears in the dashboard as a{" "}
          <code className="font-mono text-text-primary">page_view</code> event.
          Break it down by path, build funnels, or compare cohorts — all from
          the same event shape.
        </P>
      </Step>

      <Step n={5} title="Track a custom event">
        <P>
          Import the singleton in any component and call{" "}
          <code className="font-mono text-text-primary">track()</code>.
          Properties are plain values — no user IDs, no PII.
        </P>
        <div className="mt-3">
          <CodeBlock>{`// src/components/UpgradeButton.tsx\nimport { analytics } from "../analytics";\n\nexport function UpgradeButton() {\n  return (\n    <button onClick={() => analytics.track("upgrade_click", { plan: "pro" })}>\n      Upgrade\n    </button>\n  );\n}`}</CodeBlock>
        </div>
        <P>
          Your event shows up on the dashboard within a second or two. Add as
          many properties as you want — breakdowns, time series, and funnels
          compose from whatever shape you send.
        </P>
      </Step>
    </PostLayout>
  );
}
